"""initial_schema

Revision ID: 533f94445ef3
Revises:
Create Date: 2026-04-03 16:16:40.845763

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "533f94445ef3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patients",
        sa.Column("chart_no", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("sex", sa.Enum("M", "F", name="sex"), nullable=False),
        sa.Column("phone", sa.String(length=512), nullable=True),
        sa.Column("address", sa.String(length=200), nullable=True),
        sa.Column(
            "insurance_type",
            sa.Enum("건강보험", "의료급여1종", "의료급여2종", name="insurancetype"),
            nullable=False,
        ),
        sa.Column("chronic_diseases", sa.JSON(), nullable=False),
        sa.Column("allergies", sa.JSON(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("messaging_consent", sa.Boolean(), nullable=False),
        sa.Column(
            "messaging_method",
            sa.Enum("kakao", "sms", "both", name="messagingmethod"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_patients_chart_no"), ["chart_no"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("role", sa.Enum("doctor", "nurse", "admin", name="userrole"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "encounters",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_date", sa.DateTime(), nullable=False),
        sa.Column("raw_input", sa.Text(), nullable=False),
        sa.Column("subjective", sa.Text(), nullable=True),
        sa.Column("objective", sa.Text(), nullable=True),
        sa.Column("assessment", sa.Text(), nullable=True),
        sa.Column("plan", sa.Text(), nullable=True),
        sa.Column("kcd_codes", sa.JSON(), nullable=False),
        sa.Column("vitals", sa.JSON(), nullable=True),
        sa.Column("labs", sa.JSON(), nullable=False),
        sa.Column("health_promotion", sa.JSON(), nullable=True),
        sa.Column("referral_flag", sa.Boolean(), nullable=False),
        sa.Column("external_referral_note", sa.Text(), nullable=True),
        sa.Column("next_visit_date", sa.Date(), nullable=True),
        sa.Column("next_visit_tests", sa.JSON(), nullable=False),
        sa.Column("next_visit_fasting", sa.Boolean(), nullable=False),
        sa.Column(
            "visit_type", sa.Enum("초진", "재진", "건강상담", name="visittype"), nullable=False
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("encounters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_encounters_created_by"), ["created_by"], unique=False)
        batch_op.create_index(batch_op.f("ix_encounters_patient_id"), ["patient_id"], unique=False)

    op.create_table(
        "follow_up_alerts",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column(
            "alert_type",
            sa.Enum("lab_recheck", "screening_fu", "no_show", "education", name="alerttype"),
            nullable=False,
        ),
        sa.Column("item", sa.String(length=100), nullable=False),
        sa.Column("last_value", sa.String(length=50), nullable=True),
        sa.Column("last_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("days_overdue", sa.Integer(), nullable=False),
        sa.Column(
            "priority", sa.Enum("urgent", "due", "upcoming", name="alertpriority"), nullable=False
        ),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("resolved_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("follow_up_alerts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_follow_up_alerts_patient_id"), ["patient_id"], unique=False
        )

    op.create_table(
        "screening_results",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column(
            "screening_type",
            sa.Enum("국가건강검진", "암검진", "생애전환기", name="screeningtype"),
            nullable=False,
        ),
        sa.Column("screening_date", sa.Date(), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("abnormal_findings", sa.JSON(), nullable=False),
        sa.Column("follow_up_required", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("screening_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_screening_results_patient_id"), ["patient_id"], unique=False
        )

    op.create_table(
        "medical_documents",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=True),
        sa.Column(
            "doc_type",
            sa.Enum(
                "진단서",
                "소견서",
                "의뢰서",
                "확인서",
                "건강진단서",
                "검사결과안내서",
                "교육문서",
                name="doctype",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("generated_text", sa.Text(), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=True),
        sa.Column(
            "status", sa.Enum("draft", "reviewed", "issued", name="docstatus"), nullable=False
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["encounter_id"], ["encounters.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("medical_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_medical_documents_created_by"), ["created_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_medical_documents_encounter_id"), ["encounter_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_medical_documents_patient_id"), ["patient_id"], unique=False
        )

    op.create_table(
        "prescriptions",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=True),
        sa.Column("drug_name", sa.String(length=200), nullable=True),
        sa.Column("drug_code", sa.String(length=50), nullable=True),
        sa.Column("ingredient_inn", sa.String(length=200), nullable=True),
        sa.Column("atc_code", sa.String(length=50), nullable=True),
        sa.Column("drugbank_id", sa.String(length=50), nullable=True),
        sa.Column("dose", sa.String(length=50), nullable=True),
        sa.Column("frequency", sa.String(length=50), nullable=True),
        sa.Column("duration_days", sa.Integer(), nullable=True),
        sa.Column(
            "route", sa.Enum("경구", "주사", "외용", "흡입", name="drugroute"), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("prescribed_by", sa.Enum("보건소", "타원", name="prescribedby"), nullable=False),
        sa.Column("source_hospital", sa.String(length=200), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["encounter_id"], ["encounters.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("prescriptions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_prescriptions_encounter_id"), ["encounter_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_prescriptions_patient_id"), ["patient_id"], unique=False
        )

    op.create_table(
        "visit_schedules",
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("planned_tests", sa.JSON(), nullable=False),
        sa.Column("needs_fasting", sa.Boolean(), nullable=False),
        sa.Column("special_instructions", sa.JSON(), nullable=False),
        sa.Column("reminder_status", sa.JSON(), nullable=False),
        sa.Column("visit_completed", sa.Boolean(), nullable=False),
        sa.Column("created_from", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_from"], ["encounters.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("visit_schedules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_visit_schedules_patient_id"), ["patient_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("visit_schedules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_visit_schedules_patient_id"))

    op.drop_table("visit_schedules")
    with op.batch_alter_table("prescriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prescriptions_patient_id"))
        batch_op.drop_index(batch_op.f("ix_prescriptions_encounter_id"))

    op.drop_table("prescriptions")
    with op.batch_alter_table("medical_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_medical_documents_patient_id"))
        batch_op.drop_index(batch_op.f("ix_medical_documents_encounter_id"))
        batch_op.drop_index(batch_op.f("ix_medical_documents_created_by"))

    op.drop_table("medical_documents")
    with op.batch_alter_table("screening_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_screening_results_patient_id"))

    op.drop_table("screening_results")
    with op.batch_alter_table("follow_up_alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_follow_up_alerts_patient_id"))

    op.drop_table("follow_up_alerts")
    with op.batch_alter_table("encounters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_encounters_patient_id"))
        batch_op.drop_index(batch_op.f("ix_encounters_created_by"))

    op.drop_table("encounters")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_user_id"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_patients_chart_no"))

    op.drop_table("patients")
    # ### end Alembic commands ###
